window.AGROS_CATEGORIES={'oil-seeds':{label:"Oil Seeds",color:"#d4873a"},grains:{label:"Grains",color:"#c49b2e"},pulses:{label:"Pulses & Legumes",color:"#5a8a3a"},retail:{label:"Retail",color:"#3a7a8e"}},window.AGROS_PRODUCTS=[
/* ── OIL SEEDS ── */
{slug:"flaxseed-brown",name:"Brown Flaxseed",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Whole brown flaxseed — high ALA omega-3, grown on own farmland, direct from Bulgaria.",specs:[{key:"Moisture",val:"max 8%"},{key:"Purity",val:"min 99.9%"},{key:"Oil Content",val:"40–44%"},{key:"Protein",val:"20–24%"},{key:"Foreign Matter",val:"max 0.05%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["Halal & Kosher","ISO22000","FSSC22000"],relatedSlugs:["flaxseed-yellow","sunflower-seeds","mustard"],image:"Media/products/brown-flaxseed-grano.jpg"},
{slug:"flaxseed-yellow",name:"Yellow Flaxseed",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Premium golden flaxseed — mild flavour, high purity, ideal for retail and light-coloured applications.",specs:[{key:"Moisture",val:"max 8%"},{key:"Purity",val:"min 99.9%"},{key:"Oil Content",val:"38–42%"},{key:"Protein",val:"20–24%"},{key:"Foreign Matter",val:"max 0.05%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["Halal & Kosher","ISO22000","FSSC22000"],relatedSlugs:["flaxseed-brown","sunflower-seeds","oat-flakes"],image:"Media/products/golden-flaxseed-grano.jpg"},
{slug:"coriander",name:"Coriander Seeds",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Whole or split coriander seeds — essential oil min 1.1 ml/100g, spice and extraction grade.",specs:[{key:"Purity",val:"min 99.5%"},{key:"Moisture",val:"max 8%"},{key:"Essential Oil",val:"min 1.1 ml/100g"},{key:"Foreign Matter",val:"max 0.3%"},{key:"Splits",val:"available"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["Halal & Kosher","ISO22000","FSSC22000"],relatedSlugs:["mustard","flaxseed-brown","sunflower-seeds"],image:"Media/products/coriander-seed-grano.jpg"},
{slug:"sunflower-seeds",name:"Sunflower Seeds",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Whole oilseed sunflower seeds — high oil content, cleaned and dried, for pressing and processing.",specs:[{key:"Moisture",val:"max 8%"},{key:"Purity",val:"min 99%"},{key:"Oil Content",val:"42–50%"},{key:"Test Weight",val:"min 38 kg/hl"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 40ft container",tags:["Non-GMO","ISO22000","Bulgarian Origin"],relatedSlugs:["sunflower-kernels","flaxseed-brown","mustard"],image:"Media/products/sunflower-seeds.jpg"},
{slug:"sunflower-kernels",name:"Sunflower Kernels",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Hulled sunflower kernels — Bakery, Confectionery and Chips grades, purity up to 99.98%.",specs:[{key:"Grades",val:"Bakery / Confectionery / Chips"},{key:"Moisture",val:"max 7–8%"},{key:"Purity",val:"min 99.90–99.98%"},{key:"Oil Content",val:"42–52%"},{key:"Size",val:"500–700 pcs/oz"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags",moq:"1 × 40ft container",tags:["Halal & Kosher","ISO22000","FSSC22000"],relatedSlugs:["sunflower-seeds","flaxseed-brown","coriander"],image:"Media/products/sunflower-kernel-grano.jpg"},
{slug:"mustard",name:"Mustard Seeds",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Yellow and brown mustard seeds — food-grade, for spice blending, oil pressing and condiment production.",specs:[{key:"Moisture",val:"max 10%"},{key:"Purity",val:"min 99%"},{key:"Oil Content",val:"28–35%"},{key:"Volatile Oil",val:"min 0.5%"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg paper bags / 25 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["Food Grade","ISO22000","Bulgarian Origin"],relatedSlugs:["coriander","flaxseed-brown","sorghum"],image:"Media/products/mustard.jpg"},
{slug:"sorghum",name:"Sorghum",category:"oil-seeds",categoryLabel:"Oil Seeds",tagline:"Food and feed grade sorghum — gluten-free grain crop, clean and dried, for flour milling and feed.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 97%"},{key:"Protein",val:"8–12%"},{key:"Test Weight",val:"min 70 kg/hl"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 40ft container",tags:["Gluten-Free","Non-GMO","Bulgarian Origin"],relatedSlugs:["corn","mustard","sunflower-seeds"],image:"Media/products/sorghum.jpg"},
/* ── GRAINS ── */
{slug:"wheat",name:"Wheat",category:"grains",categoryLabel:"Grains",tagline:"Feed and milling wheat from Bulgaria — high protein, consistent test weight, FSSC 22000 certified supply.",specs:[{key:"Moisture",val:"max 13%"},{key:"Protein",val:"min 11%"},{key:"Test Weight",val:"min 75 kg/hl"},{key:"Gluten",val:"min 23%"},{key:"Falling Number",val:"min 220 s"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags / Bulk",moq:"1 × 40ft container",tags:["ISO22000","FSSC22000","Bulgarian Origin"],relatedSlugs:["barley","corn","oat-flakes"],image:"Media/products/wheat.jpg"},
{slug:"barley",name:"Barley",category:"grains",categoryLabel:"Grains",tagline:"Feed and malting barley — high germination, consistent test weight, for breweries and animal feed.",specs:[{key:"Moisture",val:"max 13%"},{key:"Protein",val:"9–12%"},{key:"Test Weight",val:"min 62 kg/hl"},{key:"Germination",val:"min 95%"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags / Bulk",moq:"1 × 40ft container",tags:["ISO22000","Bulgarian Origin","Non-GMO"],relatedSlugs:["wheat","oats","corn"],image:"Media/products/barley.jpg"},
{slug:"oats",name:"Oats",category:"grains",categoryLabel:"Grains",tagline:"Whole oats — food and feed grade, high protein, for milling into oat flakes and flour.",specs:[{key:"Moisture",val:"max 13%"},{key:"Protein",val:"10–15%"},{key:"Purity",val:"min 98%"},{key:"Specific Weight",val:"min 50 kg/hl"},{key:"Husked Grains",val:"max 5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["ISO22000","Gluten-Free Option","Bulgarian Origin"],relatedSlugs:["oat-flakes","wheat","barley"],image:"Media/products/oats.jpg"},
{slug:"corn",name:"Corn (Maize)",category:"grains",categoryLabel:"Grains",tagline:"Feed and food corn — non-GMO, dried and cleaned, for starch, flour, and compound feed.",specs:[{key:"Moisture",val:"max 14%"},{key:"Protein",val:"8–9%"},{key:"Test Weight",val:"min 70 kg/hl"},{key:"Foreign Matter",val:"max 1%"},{key:"Broken Grains",val:"max 3%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags / Bulk",moq:"1 × 40ft container",tags:["Non-GMO","ISO22000","Bulgarian Origin"],relatedSlugs:["wheat","barley","sorghum"],image:"Media/products/corn.jpg"},
/* ── PULSES & LEGUMES ── */
{slug:"lentils",name:"Lentils",category:"pulses",categoryLabel:"Pulses & Legumes",tagline:"Whole lentils — green and red varieties, high protein, cleaned and sorted to food grade.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 99%"},{key:"Protein",val:"22–26%"},{key:"Admixture",val:"max 0.5%"},{key:"Size",val:"4–6 mm"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["boned-lentils","peas","chickpeas"],image:"Media/products/lentils.jpg"},
{slug:"peas",name:"Peas",category:"pulses",categoryLabel:"Pulses & Legumes",tagline:"Whole yellow and green peas — food grade, for direct consumption, flour milling, and animal feed.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 99%"},{key:"Protein",val:"20–25%"},{key:"Admixture",val:"max 0.5%"},{key:"Split Grains",val:"max 2%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["split-peas","lentils","beans"],image:"Media/products/peas.jpg"},
{slug:"beans",name:"Beans",category:"pulses",categoryLabel:"Pulses & Legumes",tagline:"White and coloured beans — food grade, cleaned and sorted, for retail packing and food processing.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 99%"},{key:"Protein",val:"20–24%"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Discoloured",val:"max 1%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["chickpeas","peas","lentils"],image:"Media/products/beans.jpg"},
{slug:"chickpeas",name:"Chickpeas",category:"pulses",categoryLabel:"Pulses & Legumes",tagline:"Desi and Kabuli chickpeas — 7–9 mm and 9+ mm sizes, cleaned and sorted for food industry.",specs:[{key:"Moisture",val:"max 12%"},{key:"Purity",val:"min 99%"},{key:"Protein",val:"18–22%"},{key:"Size",val:"7–9 mm / 9+ mm"},{key:"Foreign Matter",val:"max 0.5%"},{key:"Origin",val:"Bulgaria"}],packaging:"25 kg PP bags / 50 kg PP bags / 1 000 kg Big Bags",moq:"1 × 20ft container",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["beans","peas","lentils"],image:"Media/products/chickpeas.jpg"},
/* ── RETAIL ── */
{slug:"oat-flakes",name:"Oat Flakes",category:"retail",categoryLabel:"Retail",tagline:"Rolled oat flakes — fine and thick cut, for retail packs, private label and food manufacturing.",specs:[{key:"Moisture",val:"max 13%"},{key:"Protein",val:"min 10%"},{key:"Thickness",val:"0.5–0.6 mm (fine) / 0.7–0.9 mm (thick)"},{key:"Purity",val:"min 99.5%"},{key:"Fat",val:"5–8%"},{key:"Origin",val:"Bulgaria"}],packaging:"500 g / 1 kg retail bags / 25 kg bulk bags",moq:"500 kg",tags:["Gluten-Free Option","Non-GMO","Bulgarian Origin"],relatedSlugs:["oats","split-peas","boned-lentils"],image:"Media/products/oat-flakes.jpg"},
{slug:"split-peas",name:"Split Peas",category:"retail",categoryLabel:"Retail",tagline:"Split yellow peas — dehulled and split, for soups, retail packs and food service.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 99.5%"},{key:"Protein",val:"22–26%"},{key:"Whole Peas",val:"max 2%"},{key:"Foreign Matter",val:"max 0.3%"},{key:"Origin",val:"Bulgaria"}],packaging:"500 g / 1 kg retail bags / 25 kg bulk bags",moq:"500 kg",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["peas","boned-lentils","oat-flakes"],image:"Media/products/split-peas.jpg"},
{slug:"boned-lentils",name:"Dehulled Lentils",category:"retail",categoryLabel:"Retail",tagline:"Dehulled (boned) red and green lentils — quick-cook, for retail packs, soups and food service.",specs:[{key:"Moisture",val:"max 13%"},{key:"Purity",val:"min 99.5%"},{key:"Protein",val:"24–28%"},{key:"Hulls",val:"max 0.5%"},{key:"Foreign Matter",val:"max 0.2%"},{key:"Origin",val:"Bulgaria"}],packaging:"500 g / 1 kg retail bags / 25 kg bulk bags",moq:"500 kg",tags:["High Protein","Non-GMO","Bulgarian Origin"],relatedSlugs:["lentils","split-peas","oat-flakes"],image:"Media/products/boned-lentils.jpg"}
];
